name: EssentialsPlus
version: 1.0.0-SNAPSHOT
main: com.donnie1337.essentialsplus.EssentialsPlus
api-version: '26.2'
author: donnie1337
description: Essentials customizado para Paper 26.2.
website: https://github.com/donnie1337/EssentialsPlus
softdepend:
  - ChatPlus
commands:
  tpa:
    description: Solicita teleporte até outro jogador.
    usage: /tpa <jogador>
  tpaqui:
    description: Solicita que outro jogador se teleporte até você.
    usage: /tpaqui <jogador>
  tpaceitar:
    description: Aceita uma solicitação de teleporte.
    usage: /tpaceitar [jogador]
  tpnegar:
    description: Recusa uma solicitação de teleporte.
    usage: /tpnegar [jogador]
  tpacancelar:
    description: Cancela uma solicitação de teleporte enviada.
    usage: /tpacancelar [jogador]
permissions:
  essentialsplus.tpa:
    description: Permite usar /tpa.
    default: true
  essentialsplus.tpahere:
    description: Permite usar /tpaqui.
    default: true
  essentialsplus.tpaccept:
    description: Permite aceitar solicitações de teleporte.
    default: true
  essentialsplus.tpdeny:
    description: Permite recusar solicitações de teleporte.
    default: true
  essentialsplus.tpacancel:
    description: Permite cancelar solicitações de teleporte enviadas.
    default: true
